# Generated by Django 5.1.1 on 2025-01-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='auther',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
